"main-extension-logic":
  - any-glob-to-any-file:
      - "src/*.ts"

feature:
  - head-branch: ["^feature", "feature"]

release:
  - base-branch: "main"

"explore":
  - changed-files:
      - any-glob-to-any-file:
          - "src/explore.ts"

"preview":
  - changed-files:
      - any-glob-to-any-file:
          - "src/preview.ts"

"documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"
          - "CONTRIBUTING.md"
          - "SECURITY.md"

"workspace":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
          - ".vscode/**/*"
          - ".editorconfig"
          - ".eslint*"
          - "*prettier*"
          - ".vscode-test.mjs"
          - ".vscodeignore"

"testing":
  - changed-files:
      - any-glob-to-any-file:
          - "src/test/**/*"

"configurations":
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "tsconfig.json"
