name: Issue form
description: Create an issue for the CodeArt extension.
body:
  - type: markdown
    attributes:
      value: |
        ### Is there an existing issue for this?
        Please search our [existing issues](https://github.com/uchen-ml/codeart-binexplore/issues) to see if an issue already exists for the issue you'd like to report.
  - type: textarea
    attributes:
      label: Brief Issue Summary
      description: |
        Put a short summary here.
        If this is a bug, please provide clear instructions as to how we can reproduce the issue on our end.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Optionally provide other information that will give us more context about the issue you are encountering.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
